# docker compose up -d
# docker compose --profile monitoring up -d
# version: "3.8"
services:

# Banco para dados para relatórios
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    env_file:
      - ./elasticsearch.env
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
      - elk_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - lab-elastic


networks:
  lab-elastic:
    driver: bridge

volumes:
  elk_data:
