server:
  port: 9085
  servlet:
    context-path: /labelastic
  shutdown: graceful

spring:
  application:
    name: lab-elastic

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
